"""Remove email column

Revision ID: 172ad29a41ed
Revises: 94d5276753b1
Create Date: 2025-03-22 07:03:13.753707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172ad29a41ed'
down_revision: Union[str, None] = '94d5276753b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
