"""change4

Revision ID: 1f5f2bd4319f
Revises: c9dbf6d472cc
Create Date: 2025-03-21 09:34:28.626545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5f2bd4319f'
down_revision: Union[str, None] = 'c9dbf6d472cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
